### ISSUE TITLE
Where does one get the "amd_hsmp" Linux driver?

### ISSUE THREAD

**Issue by serguei-patchkovskii** [amd/esmi_ib_library#1]
This library appears to have very limited functionality without the amd_hsmp kernel driver. This driver is not part of the latest stable kernel release (5.10 series). It does not appear in the current development kernel either, and there are no hits for either amd_hsmp or hsmp or HSMP on developer.amd.com.

Where is this driver coming from?

**Comment by nchatrad** [comment]
Hi Kostr, apologies for delayed response. To make the driver scalable and maintainable we have modified the interface, updated driver is submitted for upstream review https://www.spinics.net/lists/platform-driver-x86/msg30726.html 
a copy of the same is uploaded https://github.com/amd/amd_hsmp
