### ISSUE TITLE
It's not just 3

### ISSUE THREAD

**Issue by trinashih** [amd/esmi_ib_library#11]
https://github.com/amd/esmi_ib_library/blob/c675bb4c5c21865980ce92515db9ee29fc4d03ac/src/e_smi.c#L1750
Per HSMP function 0x21 The number should be <=5 or >6

**Comment by sumachidanand** [comment]
Yes, We will merge the necessary change. Thank you for your comment.

**Comment by nchatrad** [comment]
https://github.com/amd/esmi_ib_library/commit/1a2599ed62e411270b9264828ba71c790e0ec12d address the request. thank you.
