### ISSUE TITLE
sudo ./e_smi_tool --showsockettemp

### ISSUE THREAD

**Issue by trinashih** [amd/esmi_ib_library#17]
when run this command(e_smi_tool --showsockettemp), and I received below outputs:
============================= E-SMI ===================================

------------------------------------------------------------------------
| Sensor Name                    | Socket 0         | Socket 1         |
------------------------------------------------------------------------
| Temperature                    | NA (Err: 20)     | NA (Err: 20)     |
------------------------------------------------------------------------
Err[20]: HSMP message/command not supported

============================= End of E-SMI ============================

I'm trying to read the Die temps or CCD temps. 

Thanks

**Comment by sumachidanand** [comment]
E_smi_tool doesn't support reading temperature feature on all the platforms.
Which platform are you using?

**Comment by trinashih** [comment]
Ah.. got it. I tried this on Turin. Thanks
