### ISSUE TITLE
system parametrs modification rights

### ISSUE THREAD

**Issue by vysocky** [amd/esmi_ib_library#4]
To change system settings using the e_smi64 library it is necessary to have sudo rights. How can we raise rights for a specific group of user for the library (not the utility)?
It would be nice to have something like [msr-safe](https://github.com/LLNL/msr-safe) interface to control the access.
Thank you

**Comment by nchatrad** [comment]
esmi_ib_library depends on amd_energy driver and amd_hsmp driver. The access restrictions are brought by these drivers in the kernel space throught the respective device files"/sys/class/hwmon/hwmonX/energyX_input" and "/dev/hsmp" .
All the set/configure operations are restricted to root
All get/monitor operations are allowed for all the users.
